[package]
name = "tfc-exes"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["display"] }
smlang = { version = "0.8.0", features = ["graphviz"] }
tfc = { git = "https://github.com/centroid-is/tfc.git", tag = "2024.9.1" }
