[package]
name = "tfc-exes"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["display"] }
futures = "0.3.30"
futures-channel = "0.3.30"
log = "0.4.22"
parking_lot = { version = "0.12.3", features = ["arc_lock"] }
schemars = "0.8.21"
serde = "1.0.210"
smlang = { version = "0.8.0", features = ["graphviz"] }
# tfc = { git = "https://github.com/centroid-is/tfc.git", tag = "2024.9.1" }
tfc = { path = "../framework-rs"}
tokio = "1.40.0"
zbus = "4.4.0"
