name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y mold lld clang
    - uses: actions/checkout@v4
    - name: Copy dbus-tfc.conf
      run: |
        sudo cp dbus-tfc.conf /etc/dbus-1/system.d/
        sudo sed -i 's|deny own=|allow own=|g' /usr/share/dbus-1/system.conf
        sudo sed -i 's|deny send_type="method_call"|allow send_type="method_call"|g' /usr/share/dbus-1/system.conf
        sudo /usr/bin/busctl call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ReloadConfig
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        RUNTIME_DIRECTORY: /tmp/
        CONFIGURATION_DIRECTORY: /tmp/
      run: cargo test --verbose
